//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectAlpha.Models
{
    using System;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Resources;
    using System.Data.Entity.Infrastructure;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Archive
    {
        public Archive(string link, string archiveLink, string repoLink, string shortDesc, string longDesc, byte[] snapShot, string userID, string projectName, string teamName, AspNetUser aspNetUser = null)
        {
            Link = link;
            ArchiveLink = archiveLink;
            RepoLink = repoLink;
            ShortDesc = shortDesc;
            LongDesc = longDesc;
            SnapShot = snapShot;
            UserID = userID;
            ProjectName = projectName;
            ArchiveDate = DateTime.Today;
            TeamName = teamName;
            this.AspNetUser = aspNetUser;
        }
        public Archive()
        {
        }
        //Sets validation message and data type.
        [Key]
        [DisplayName("Project Link")]
        [Required(ErrorMessage = "Required Field")]
        [Url(ErrorMessage = "Please enter a valid url")]
        [DataType(DataType.Url)]
        public string Link { get; set; }

        [Required(ErrorMessage = "Required Field")]
        [Url(ErrorMessage = "Please enter a valid url")]
        [DataType(DataType.Url)]
        public string ArchiveLink { get; set; }

       
        [Url(ErrorMessage = "Please enter a valid url")]
        [DataType(DataType.Url)]
        public string RepoLink { get; set; }

        [Required(ErrorMessage = "Please enter between 10-200 characters")]
        [StringLength (maximumLength: 200, MinimumLength=10)]
        [DataType(DataType.MultilineText)]
        public string ShortDesc { get; set; }

        [StringLength(500,  MinimumLength = 20)]
        [Description ("Please enter between 20-500 characters")]
        public string LongDesc { get; set; }

        //[DataType(DataType.Upload)] Verify using upload.
        public byte[] SnapShot { get; set; }

        //[EmailAddress]
        [DataType(DataType.EmailAddress)]
        public string UserID { get; set; }

        [Required(ErrorMessage = "Please enter a name for your project")]
        [StringLength(50)]
        public string ProjectName { get; set; }


        public System.DateTime ArchiveDate { get; set; }

        [StringLength(50)]
        public string TeamName { get; set; }
    //[ForeignKey(AspNetUser)]
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
