//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectAlpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public Archive()
        {
        }
        public Archive(string link, string archiveLink, string repoLink, string shortDesc, string longDesc)
        {
            Link = link;
            ArchiveLink = archiveLink;
            RepoLink = repoLink;
            ShortDesc = shortDesc;
            LongDesc = longDesc;
        }

        public Archive(string link, string archiveLink, string shortDesc)
        {
            Link = link;
            ArchiveLink = archiveLink;
            ShortDesc = shortDesc;
        }

        public string Link { get; set; } 
        public string ArchiveLink { get; set; }
        public string RepoLink { get; set; } //nullable
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; } //nullable
    }
}
